#ifndef DISPLAYGRAPH3D_GLOBAL_H
#define DISPLAYGRAPH3D_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYGRAPH3D_LIBRARY)
#  define DISPLAYGRAPH3DSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYGRAPH3DSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYGRAPH3D_GLOBAL_H
