#ifndef DISPLAYINFORMATION_GLOBAL_H
#define DISPLAYINFORMATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYINFORMATION_LIBRARY)
#  define DISPLAYINFORMATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYINFORMATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYINFORMATION_GLOBAL_H
